### ISSUE TITLE
LA SUGGESTION C'EST DE NOUS DEBLOQUER ON VA COMMENCER PAR CA

### ISSUE THREAD

**Issue by Truc742** [julmanbot/julmanbot.github.io#20]
DONC MAINTENANT TU LE FAIS OU ENORME GAY

**Comment by JulMan-Dev** [comment]
bah non

**Comment by JulMan-Dev** [comment]
![image](https://user-images.githubusercontent.com/68107155/135130642-dbf0c263-355f-411b-964f-5e2c327da606.png)
